name: Python Lint

on:
  push:
  pull_request:
    paths:
      - ".github/**"
      - "python/**"
      - "crates/**/*.py"
      - "scripts/**/*.py"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Format Check
        run: hatch fmt --check
